#!/bin/bash
echo for_loop_samp was generated by the "newbash.sh" script.

echo this file loops through all the bash scripts in the current directory
echo and counts them.

for file in $(ls ./*.sh);
do
    let i++
    #echo "bash script $file"
done
echo The number of bash scripts in this directory is $i
