#!/bin/bash

if [ $# -ne 1 ]
then
    echo "Please enter the shell name as the first argument, no need for \".sh\""
    exit 1
elif [ $# -ge 2 ]
then
    echo "Please enter only one shell name, no need for \".sh\""
    exit 1
elif [ -f $1.sh ]
then
    echo "shell $1.sh already exists in this directory, please choose another name or delete.
    this bash script will not overwrite existing files."
    exit 1
else
    echo "generating new sample shell $1"
    touch $1.sh # create file 
    echo "#!/bin/bash" > $1.sh # add shebang
    echo "echo $1 was generated by the \"newbash.sh\" script." >> $1.sh # add shebang
    chmod 755 $1.sh # make it executable
    echo "new shell created, just add code"
    exit 0
fi
