#!/bin/bash
echo whileCntTo100 was generated by the "newbash.sh" script.

echo this file counts to 100 using a while loop
i=0
while [ $i -lt 100 ]
do
    let i++
    echo $i
done
echo The number of times the loop was executed is $i
exit 0